name: srp_drive
version: 1.0.0+1
publish_to: none
description: A Google Drive Copy.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: 5.1.0
  eva_icons_flutter: 3.1.0
  get: 4.6.5
  google_sign_in: 6.1.4
  firebase_core: 2.15.0
  firebase_auth: 4.7.2
  cloud_firestore: 4.8.4
  firebase_storage: 11.2.5
  file_picker: 5.3.3
  mime: 1.0.4
  path_provider: 2.0.15
  uuid: 3.0.7
  flutter_image_compress: 2.0.4
  flutter_ffmpeg: 0.4.2
  video_compress: 3.1.2
  url_launcher: 6.1.12
  audioplayers: 5.0.0
  chewie: 1.7.0
  video_player: 2.7.0
  flutter_downloader: 1.11.0
  permission_handler: 10.4.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

