name: srp_drive
version: 1.0.0+1
publish_to: none
description: A Google Drive Copy.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # State Management
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  # eva_icons_flutter: 3.1.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  file_picker: ^8.0.3
  # mime: ^1.0.5
  path_provider: ^2.1.2
  uuid: ^4.3.3
  # flutter_image_compress: ^2.2.0
  # flutter_ffmpeg: 0.4.2
  # video_compress: 3.1.2
  url_launcher: ^6.2.5
  audioplayers: ^5.2.1
  chewie: ^1.7.5
  video_player: ^2.8.3
  # flutter_downloader: 1.11.0
  permission_handler: ^11.3.0
  flutter_dotenv: 5.1.0
  shared_preferences: ^2.2.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - .env

